### ISSUE TITLE
微信登录成功判断

### ISSUE THREAD

**Issue by klren0312** [Guing/Wechat-Admin-API#1]
前端登录后, 需要有接口(或者ws?)来获取是否登录成功
 - 把checkLogin引出接口
 - 或者搞个ws, 前端把userId传给后端, 轮询状态

**Comment by Guing** [comment]
已添加`/api/wechat/isLogin`接口

**Comment by Guing** [comment]
> 前端登录后, 需要有接口(或者ws?)来获取是否登录成功
> 
> * 把checkLogin引出接口
> * 或者搞个ws, 前端把userId传给后端, 轮询状态
